github:
  scope: org
  url: https://github.com
  org: lsc-sde
  repository: iac-helm-github-actions-runner
  enterpriseName: lsc-sde
  api:
    url: "https://api.github.com"

runner:
  image: myoung34/github-runner:latest
  group: github-actions-runner-k8s
  labels: testLabel
  replicas:
    minimum: 1
    maximum: 5

  resources:
    requests:
      cpu: 2
      memory: 256Mi

  nodeSelector: {}
  tolerations: {}
  workVolume: []
  extraVolumes: []
  extraVolumeMounts: []

dind-daemon:
  image: docker:25.0.1-dind

accessToken:
  secretName: testSecret
  secretKey: testSecretKey

  