apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.runner.replicas.minimum }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app-type: actions-runner
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app-type: actions-runner
    spec:
      nodeSelector:
        {{- toYaml .Values.runner.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.runner.tolerations | nindent 8 }}
        
      volumes:
      - name: containerdsock
        hostPath:
          path: /run/containerd/containerd.sock
      {{ if .Values.runner.workVolume }}
      {{ toYaml .Values.runner.workVolume | nindent 6 }}
      {{ else }}
      - name: workdir
        hostPath:
          path: {{ include "github-actions-runner.workdir" . }}
      {{ end }}
      {{ if .Values.runner.extraVolumes }}
      {{ toYaml .Values.runner.extraVolumes | nindent 6 }}
      {{ end }}

      containers:
      #- name: dind-daemon
      #  image: {{ .Values.dind.image }}
      #  command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
      #  securityContext:
      #    privileged: true
      #  volumeMounts:
      #    - name: workdir
      #      mountPath: /var/lib/docker

      - name: runner
        image: {{ .Values.runner.image }}
        env:
        - name: START_DOCKER_SERVICE
          value: "false"
        
        #- name: DOCKER_HOST
        #  value: tcp://localhost:2375
        
        #- name: DOCKER_API_VERSION
        #  value: "1.42"
        
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.accessToken.secretName }}
              key: {{ .Values.accessToken.secretKey }}
        
        - name: RUNNER_SCOPE
          value: {{ .Values.github.scope }}
          
        {{ if eq .Values.github.scope "org" }}
        - name: ORG_NAME
          value: {{ .Values.github.org }}
        {{ end }}

        {{ if eq .Values.github.scope "repo" }}
        - name: REPO_URL
          value: {{ include "github-actions-runner.repourl" . }}
        {{ end }}

        {{ if eq .Values.runner.scope "enterprise" }}
        - name: ENTERPRISE_NAME
          value: {{ .Values.github.enterpriseName }}
        {{ end }}

        - name: LABELS
          value: {{ .Values.runner.labels }}

        - name: RUNNER_NAME_PREFIX
          value: git

        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: RUNNER_WORKDIR
          value: {{ include "github-actions-runner.workdir" . }}

        - name: RUNNER_GROUP
          value: {{ .Values.runner.group }}
        
        volumeMounts:
        - name: containerdsock
          mountPath: /run/containerd/containerd.sock

        - name: workdir
          mountPath: /tmp
          
        {{ if .Values.runner.extraVolumeMounts }}
        {{ toYaml .Values.runner.extraVolumeMounts | nindent 8 }}
        {{ end }}
          
        securityContext:
          privileged: true # Required to enable img
        
        resources:
          {{- toYaml .Values.runner.resources | nindent 10 }}