apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.runner.replicas.minimum }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app-type: actions-runner
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app-type: actions-runner
    spec:
      affinity:
        {{- toYaml .Values.runner.affinity | nindent 8 }}
        
      volumes:
      - name: containerdsock
        hostPath:
          path: /run/containerd/containerd.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-your-repo
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: START_DOCKER_SERVICE
          value: "true"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.accessToken.secretName }}
              key: {{ .Values.accessToken.secretKey }}
        - name: RUNNER_SCOPE
          value: {{ .Values.runner.scope }}
          
        {{ if eq .Values.runner.scope "org" }}
        - name: ORG_NAME
          value: {{ .Values.github.org }}
        {{ end }}

        {{ if eq .Values.runner.scope "repo" }}
        - name: REPO_URL
          value: {{ include "github-actions-runner.repourl" . }}
        {{ end }}

        {{ if eq .Values.runner.scope "enterprise" }}
        - name: ENTERPRISE_NAME
          value: {{ .Values.github.enterpriseName }}
        {{ end }}

        - name: LABELS
          value: {{ .Values.runner.labels }}

        - name: RUNNER_NAME_PREFIX
          value: git

        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-your-repo

        - name: RUNNER_GROUP
          value: {{ .Values.runnerGroup }}
        
        volumeMounts:
        - name: containerdsock
          mountPath: /run/containerd/containerd.sock

        - name: workdir
          mountPath: /tmp/github-runner-your-repo
        
        securityContext:
          privileged: true # Required if you're enabling docker
        
        resources:
          {{- toYaml .Values.runner.resources | nindent 10 }}