apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: {{ .Values.runner.replicas.minimum }}
  maxReplicaCount: {{ .Values.runner.replicas.maximum }}
  triggers:
  - type: github-runner
    metadata:
      githubAPIURL: {{ .Values.github.api.url }}
      owner: {{ .Values.github.org }}
      runnerScope: {{ .Values.github.scope }}
      {{ if eq .Values.github.scope "repo" }}
      repos: {{.Values.github.repository }}
      {{ end }}
      labels: {{ .Values.runner.labels }}
      targetWorkflowQueueLength: "1"
    authenticationRef:
     name: {{ .Release.Name }}